/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function z85Dump(bin: Bin): string
export function z85Load(s: string): Uint8Array
export function ipBin(ip: string): Uint8Array
export function binU64(bin: Uint8Array): number
export function u64Bin(i: number): Uint8Array
export function zipU64(li: Array<number>): Uint8Array
export function unzipU64(li: Uint8Array, len: number): Array<number>
export function b64(input: Bins): string
export function unb64(input: Bin): Uint8Array
export function blake3Round(data: Bins, round: number): Promise<unknown>
export function blake3(input: Bins): Uint8Array
export function xxh3(input: Bins): bigint
export function encrypt(secret: Bin, iv: Bin, data: Bin): Uint8Array
export function decrypt(secret: Bin, iv: Bin, data: Bin): Uint8Array | null
export function randomBytes(n: number): Uint8Array
